spring:
 autoconfigure:
   exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
            org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,
            org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
 cloud:
   gateway:
     routes:
      # TODO: Lengkapi route untuk gateway
      - id: master-service
        uri: http://localhost:9092
        predicates:
          - Path=/api/v1/master-service/**
        filters:
          - StripPrefix=3

      - id: web-forum-service
        uri: http://localhost:9093
        predicates:
          - Path=/api/v1/web-forum-service/**
        filters:
          - StripPrefix=3
      
      - id: auth-service
        uri: http://localhost:9094
        predicates:
          - Path=/api/v1/auth-service/**
        filters:
          - StripPrefix=3

      - id: advertisement-service
        uri: http://localhost:9095
        predicates:
          - Path=/api/v1/advertisement-service/**
        filters:
          - StripPrefix=3
          
 application:
   name: API-GATEWAY


